language: php

php:
    - 5.6
    - 7.0
    - hhvm

notifications:
    email:
        on_success: never
        on_failure: change

before_script:
    - composer install

script:
    - vendor/bin/phpunit
