language: php

php:
    - 5.6
    - 7.0
    - hhvm

notifications:
    email:
        on_success: never
        on_failure: change

install: composer install

before_script:
    - composer validate --strict
    - mkdir -p build/logs

script: vendor/bin/phpunit

after_success: travis_retry php vendor/bin/coveralls -v
