language: php

php:
    - 5.5
    - 5.6
    - 7.0

env:
    - WP_CLI_BIN_DIR="$TRAVIS_BUILD_DIR/vendor/bin"

install: composer install

before_script:
    - composer validate --strict
    - mkdir -p build/logs
    - mysql -e 'CREATE DATABASE wp_cli_test;' -uroot
    - mysql -e 'GRANT ALL PRIVILEGES ON wp_cli_test.* TO "wp_cli_test"@"localhost" IDENTIFIED BY "password1"' -uroot

script:
    - vendor/bin/phpunit
    - vendor/bin/behat

after_success: travis_retry php vendor/bin/coveralls -v

cache:
  directories:
    - vendor

notifications:
    email:
        on_success: never
        on_failure: change
