name: Test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        php-version: ['8.2', '8.1', '8.0', '7.0']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Validate composer.json
        run: composer validate --strict

      - run: composer install

      - run: composer test
